# Literature

*Some literature on approaches to synthetic population generation:*

**PopGen**

> **Synthetic population generator: PopGen (Mobility Analytics Research Group, 2016)** 

> **Enhanced synthetic population generator that accomodates control variables at multiple geographic resolutions (Konduri, You, Garikapati, and Pendyala, 2016)** 

> **A methodology to match distributions of both household and person attributes in the generation of synthetic populations (Ye, Konduri, Pendyala, Sana, and Waddell, 2009)** 




The PopGen software [@marg2016] was designed by the Mobility Analytics Research Group, with the main team of scientists cited in the second source above [@konduri2016], and was last updated in 2016. 

The methodology was presented at the 8th Annual Meeting of the Transportation Research Board in Washington, D.C., USA and is described in [@ye2009]. 

*N.B. Might want more here but methods are mathematically complex; requires further reading.* 

**PopGen v. PopSynWin**

> **Creating a synthetic population: A comparison of tools (Jain, Ronald, and Winter, 2015)** 

This article was produced for the 3rd Conference of the Transportation Research Group of India by a group of infrastructure engineers at The University of Melbourne, Australia [@jain_2015]. The work generates and compares synthetic populations using two software programs: PopSynWin (iterative proportional fitting algorithm) and PopGen (see above, iterative proportional update algorithm). Differences between actual and synthesized population characteristics are presented. Authors concluded that the PopGen software yielded better results, with closer matches of person level characteristic distributions to that of the actual population. 


**synthpop R**

> **synthpop: Bespoke Creation of Synthetic Data in R (Nowok, Raab, & Dibben, 2016)** 

The [synthpop](https://www.jstatsoft.org/article/view/v074i11) R package was published in 2016 and is described in [@nowok2016] with a step-by-step example. 

  - Can choose between several sampling method options to develop synthetic data: 
  
    - random sample from observed data (default)
    - function of other synthesized data
    - non-parametric methods: [classification and regression trees](https://cran.r-project.org/web/packages/rpart/index.html)
    - parametric methods: synthesis based on variable type (numeric, binary, unordered and order factors)
      - normal linear regression (preserving marginal distribution/not)
      - logistic regression
      - (ordered/not) polytomous logistic regression
      - predictive mean matching)
