--- 
title: "Synthetic population generation for ACRES project"
author: "Flannery Black-Ingersoll and Chad Milando"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [articles.bib, packages.bib, zotero.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This book describes the process and applications of using the CO model to create a synthetic population for MyWRA, and estimate the impact of climate-change adaptation efforts."
---

# Prerequisites

Here we will describe the overall purpose of the project, with some links.
and probably embed and image or two.


```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(tigris)
library(leaflet) #https://rstudio.github.io/leaflet/basemaps.html
library(sf)
library(dplyr)
library(utils)
library(readr)
# Plot tract polygons and puma polygons together
MA_pumas <- pumas(state = "MA", year = 2021)
pumas <- c("00503",
           "00505",
           "02800",
           "01000",
           "00508",
           "00507",
           "00506",
           "03302",
           "00505",
           "03306",
           "01300")
MA_pumas_mywra <- subset(MA_pumas, MA_pumas$PUMACE10 %in% pumas)
MA_tracts <- tracts(state = "MA", year = 2021)

my_dir <- "mywra_tractsbypuma/"
PUMA00503 <- readRDS(paste0(my_dir,"PUMA00503.rds"))
PUMA00503 <- unique(substr(PUMA00503$PUMACE10, 6,11))
PUMA00503_tracts <- subset(MA_tracts,MA_tracts$TRACTCE %in% PUMA00503)
  
PUMA00505 <- readRDS(paste0(my_dir,"PUMA00505.rds"))
PUMA00505 <- unique(substr(PUMA00505$PUMACE10, 6,11))
PUMA00505_tracts <- subset(MA_tracts,MA_tracts$TRACTCE %in% PUMA00505)

PUMA00506 <- readRDS(paste0(my_dir,"PUMA00506.rds"))
PUMA00506 <- unique(substr(PUMA00506$PUMACE10, 6,11))
PUMA00506_tracts <- subset(MA_tracts,MA_tracts$TRACTCE %in% PUMA00506)

PUMA00507 <- readRDS(paste0(my_dir,"PUMA00507.rds"))
PUMA00507 <- unique(substr(PUMA00507$PUMACE10, 6,11))
PUMA00507_tracts <- subset(MA_tracts,MA_tracts$TRACTCE %in% PUMA00507)

PUMA00508 <- readRDS(paste0(my_dir,"PUMA00508.rds"))
PUMA00508 <- unique(substr(PUMA00508$PUMACE10, 6,11))
PUMA00508_tracts <- subset(MA_tracts,MA_tracts$TRACTCE %in% PUMA00508)

PUMA01000 <- readRDS(paste0(my_dir,"PUMA01000.rds"))
PUMA01000 <- unique(substr(PUMA01000$PUMACE10, 6,11))
PUMA01000_tracts <- subset(MA_tracts,MA_tracts$TRACTCE %in% PUMA01000)

PUMA01300 <- readRDS(paste0(my_dir,"PUMA01300.rds"))
PUMA01300 <- unique(substr(PUMA01300$PUMACE10, 6,11))
PUMA01300_tracts <- subset(MA_tracts,MA_tracts$TRACTCE %in% PUMA01300)

PUMA02800 <- readRDS(paste0(my_dir,"PUMA02800.rds"))
PUMA02800 <- unique(substr(PUMA02800$PUMACE10, 6,11))
PUMA02800_tracts <- subset(MA_tracts,MA_tracts$TRACTCE %in% PUMA02800)

PUMA03302 <- readRDS(paste0(my_dir,"PUMA03302.rds"))
PUMA03302 <- unique(substr(PUMA03302$PUMACE10, 6,11))
PUMA03302_tracts <- subset(MA_tracts,MA_tracts$TRACTCE %in% PUMA03302)

PUMA03306 <- readRDS(paste0(my_dir,"PUMA03306.rds"))
PUMA03306 <- unique(substr(PUMA03306$PUMACE10, 6,11))
PUMA03306_tracts <- subset(MA_tracts,MA_tracts$TRACTCE %in% PUMA03306)


map_2 <- leaflet() %>%
  setView(lat = 42.48, lng = -71.09, zoom = 10) %>%
  addProviderTiles(
    providers$Esri.WorldTopoMap,
    options = providerTileOptions(opacity = 0.75),
    group = "ESRI World Topographic") %>%
   addProviderTiles(
    providers$Esri.WorldGrayCanvas,
    options = providerTileOptions(opacity = 0.75),
    group = "ESRI World Gray Canvas") %>%
  addProviderTiles(
    providers$Esri.WorldImagery,
    options = providerTileOptions(opacity = 0.75),
    group = "ESRI World Imagery") %>%
    addPolygons(
    data = PUMA00503_tracts,
    # set the color of outlines
    stroke = T,
    color = "red",
    fill = F,
    # set the opacity of the outline
    # set the stroke width in pixels
    weight = 1.4,
    group = "PUMA 00503 Census Tracts",
    popup = ~TRACTCE
   ) %>%
  addPolygons(
    data = PUMA00505_tracts,
    # set the color of outlines
    stroke = T,
    color = "blue",
    fill = F,
    # set the opacity of the outline
    # set the stroke width in pixels
    weight = 1.4,
    group = "PUMA 00505 Census Tracts",
    popup = ~TRACTCE
   ) %>%
  addPolygons(
    data = PUMA00506_tracts,
    # set the color of outlines
    stroke = T,
    color = "orange",
    fill = F,
    # set the opacity of the outline
    # set the stroke width in pixels
    weight = 1.4,
    group = "PUMA 00506 Census Tracts",
    popup = ~TRACTCE
   ) %>%
  addPolygons(
    data = PUMA00507_tracts,
    # set the color of outlines
    stroke = T,
    color = "darkgreen",
    fill = F,
    # set the opacity of the outline
    # set the stroke width in pixels
    weight = 1.4,
    group = "PUMA 00507 Census Tracts",
    popup = ~TRACTCE
   ) %>%
  addPolygons(
    data = PUMA00508_tracts,
    # set the color of outlines
    stroke = T,
    color = "magenta",
    fill = F,
    # set the opacity of the outline
    # set the stroke width in pixels
    weight = 1.4,
    group = "PUMA 00508 Census Tracts",
    popup = ~TRACTCE
   ) %>%
  addPolygons(
    data = PUMA01000_tracts,
    # set the color of outlines
    stroke = T,
    color = "purple",
    fill = F,
    # set the opacity of the outline
    # set the stroke width in pixels
    weight = 1.4,
    group = "PUMA 01000 Census Tracts",
    popup = ~TRACTCE
   ) %>%
  addPolygons(
    data = PUMA01300_tracts,
    # set the color of outlines
    stroke = T,
    color = "goldenrod",
    fill = F,
    # set the opacity of the outline
    # set the stroke width in pixels
    weight = 1.4,
    group = "PUMA 01300 Census Tracts",
    popup = ~TRACTCE
   ) %>%
  addPolygons(
    data = PUMA02800_tracts,
    # set the color of outlines
    stroke = T,
    color = "tan",
    fill = F,
    # set the opacity of the outline
    # set the stroke width in pixels
    weight = 1.4,
    group = "PUMA 02800 Census Tracts",
    popup = ~TRACTCE
   ) %>%
  addPolygons(
    data = PUMA03302_tracts,
    # set the color of outlines
    stroke = T,
    color = "pink",
    fill = F,
    # set the opacity of the outline
    # set the stroke width in pixels
    weight = 1.4,
    group = "PUMA 03302 Census Tracts",
    popup = ~TRACTCE
   ) %>%
  addPolygons(
    data = PUMA03306_tracts,
    # set the color of outlines
    stroke = T,
    color = "maroon",
    fill = F,
    # set the opacity of the outline
    # set the stroke width in pixels
    weight = 1.4,
    group = "PUMA 03306 Census Tracts",
    popup = ~TRACTCE
   ) %>%
   addPolygons(
    data = MA_pumas_mywra,
    # set the color of outlines
    stroke = T,
    color = "black",
    fill = F,
    # set the opacity of the outline
    # set the stroke width in pixels
    weight = 1.4,
    group = "All Public Use Microdata Areas",
    popup = ~NAMELSAD10
   )%>%
  # Layers control
  addLayersControl(
    baseGroups = c("ESRI World Topographic",
                   "ESRI World Gray Canvas",
                   "ESRI World Imagery"),
    overlayGroups = c("All Public Use Microdata Areas",
      "PUMA 00503 Census Tracts",
           "PUMA 00505 Census Tracts",
           "PUMA 02800 Census Tracts",
           "PUMA 01000 Census Tracts",
           "PUMA 00508 Census Tracts",
           "PUMA 00507 Census Tracts",
           "PUMA 00506 Census Tracts",
           "PUMA 03302 Census Tracts",
           "PUMA 00505 Census Tracts",
           "PUMA 03306 Census Tracts",
           "PUMA 01300 Census Tracts"),
    options = layersControlOptions(collapsed = FALSE)
  )

# side note... look how beautiful this is: -->
# leaflet() %>%
# setView(lat = 42.40, lng = -71.09713377834885, zoom = 10) %>%
# addProviderTiles(providers$Stamen.Watercolor)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
map_2
```


